@tool
class_name MovementCorrectionSurface
extends Area3D

@export_group("Movement Correction Surface")

@export_subgroup("Activation")
## Enables this correction surface.
@export var correction_enabled: bool = true
## Physics layer queried by player movement correction.
@export_flags_3d_physics var correction_collision_layer: int = 1 << 8:
	set(value):
		correction_collision_layer = value
		collision_layer = value

@export_subgroup("Strength")
## Multiplies the correction generated by this surface.
@export var strength_multiplier: float = 1.0
## Minimum player speed required for this surface to contribute correction.
@export var minimum_speed: float = 0.0
## Player speed where this surface reaches full strength.
## Values at or below minimum speed apply full strength immediately.
@export var full_strength_speed: float = 120.0


func _ready() -> void:
	collision_layer = correction_collision_layer
	collision_mask = 0
	monitoring = false
	monitorable = true


func get_movement_correction_strength(speed: float) -> float:
	if not correction_enabled:
		return 0.0
	var minimum: float = max(minimum_speed, 0.0)
	if speed < minimum:
		return 0.0
	var full_speed: float = max(full_strength_speed, minimum)
	var speed_scale: float = 1.0
	if full_speed > minimum:
		speed_scale = clamp((speed - minimum) / (full_speed - minimum), 0.0, 1.0)
	return max(strength_multiplier, 0.0) * speed_scale
